sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t siddharthsal99/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true siddharthsal99/docker-react npm run test

# added a comment to trigger build